### ISSUE TITLE
Add ability to fetch issues with no member comments

### ISSUE THREAD

**Issue by drazisil** [drazisil/dashboard-zero#10]
- [ ] Database
- [ ] API
- [ ] View

A metric from #2 

https://api.github.com/repos/adamlofting/dashboard-zero/issues/comments
Or 
https://api.github.com/repos/adamlofting/dashboard-zero/issues/1/comments

Likely use the comment totals (am i pulling those?) from the issues feed to decide if its better to parse issues one at a time, or in batches of 100.

**Comment by drazisil** [comment]
Added formula to codebook #14

**Comment by gsilvapt** [comment]
To check it if the team commented on that, we can try to match the user_id with the members list and, if it is a match, then return as TRUE (and do more calculations with it). If it is not, then returns FALSE (and do other calculations with it).

**Comment by drazisil** [comment]
Going with just untouched issues for v1.0

**Comment by drazisil** [comment]
Still want
