### ISSUE TITLE
Add last updated metric to issues list

### ISSUE THREAD

**Issue by drazisil** [drazisil/dashboard-zero#13]

**Comment by gsilvapt** [comment]
We should try to find an automated way to do this. Is it possible? If we manage to save in a specific location, with a specific name, I'm sure I can manage to do a R script that will read it, process it, do the work and save it with another name - something like day/month/year and keep everything stored somewhere.

In the future we can even produce historical analysis, but I'm not sure if the true stakeholders of this project will appreciate such thing

**Comment by drazisil** [comment]
When I say last updates, I meant there's a last updates time stamp I'm not grabbing. It's actually sorta automated now, but I would love to archive it. *I* like historical trends anyway :-)

**Comment by gsilvapt** [comment]
Oh, cool then. The next script I'll make will contemplate that feature then - fetch it, treat it, store it somewhere - probably in a folder called (stored data) :)

**Comment by drazisil** [comment]
This has been added
