### ISSUE TITLE
Build a reporting dashboard

### ISSUE THREAD

**Issue by drazisil** [drazisil/dashboard-zero#3]
Thinking either d3 or http://metricsgraphicsjs.org/

Probably Angular would be good for this. 

https://projects.invisionapp.com/m/share/3T37KEZ5D?standalone=false#/82586611 Looks really nice, love the pods. 

https://files.slack.com/files-pri/T055D2Z1N-F074B6WLA/dashboard_ui.png Looks great, black always works well for programmers, we dont do light. 

Theres also the origiknal sketch https://docs.google.com/drawings/d/1t6Ttdk8LHT0fKy12xxmaxmIFUV5AuA7eeMGqnnH-Epw/edit?usp=sharing which i really like, maybe with headers, and drilldown to the details

**Comment by drazisil** [comment]
So. Many beautiful things with https://github.com/mbostock/d3/wiki/Gallery, when all I want is circles and numbers.

**Comment by gsilvapt** [comment]
Beware that you may not be able to use all plots from the that last gallery and some of them are not useful for now, I believe :)

**Comment by drazisil** [comment]
Display pretty much exists, moving to someday for now as I want to revisit the dashboards.

**Comment by drazisil** [comment]
How do you even get pods like this (https://files.slack.com/files-pri/T055D2Z1N-F074B6WLA/dashboard_ui.png) anymore?

**Comment by drazisil** [comment]
http://patternry.com/p=drag-and-drop-modules/

**Comment by drazisil** [comment]
Still want this
